name: Publish to PyPI

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  id-token: write  # For trusted publishing

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release  # Optional: creates deployment protection
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Build package
      run: uv build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # Use trusted publishing (recommended) or API token
        # For trusted publishing, configure on PyPI: https://pypi.org/manage/account/publishing/
        # For API token, add PYPI_API_TOKEN to repository secrets
        password: ${{ secrets.PYPI_API_TOKEN }}